server:
  port: 8001 #服务端口
#spring相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库驱动包
    url: jdbc:mysql://49.235.115.50:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: itongji123456


management:
  endpoints:
    jmx:
      exposure:
        include: '*'

#mybatis:配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.test.cloud.pojo    # 所有pojo别名类所在包